### ISSUE TITLE
Copy Token

### ISSUE THREAD

**Issue by hansputera** [hansputera/discord-experiment-login#1]
Copy Token and Paste in Console.

**Comment by InsiderJanggo** [comment]
what do you mean copy paste token in console ?

**Comment by hansputera** [comment]
scrape token on discord.com/developers and paste in console. Can you help?

**Comment by hanahaneull** [comment]
Discord have API for this, why would you need to use puppeteer?

**Comment by hansputera** [comment]
im boring

**Comment by hansputera** [comment]
I have found many bugs and i will solve that, thanks.
